version: "3"
services:

  authentication-db:
    build: authService/authenticationDB

  delivery-db:
    build: deliveryService/deliveryDB

  discovery-service:
    build: discoveryService
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=discovery-service

  auth-service:
    build: authService
    depends_on:
      - authentication-db
      - discovery-service
    environment:
      - EUREKA_SERVER_ADDRESS=discovery-service
      - MONGODB_HOST=authentication-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=auth

  delivery-service:
    build: deliveryService
    depends_on:
      - delivery-db
      - discovery-service
    environment:
      - EUREKA_SERVER_ADDRESS=discovery-service
      - MONGODB_HOST=delivery-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=delivery

  gateway-service:
    build: gatewayService
    ports:
      - "10789:10789"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_SERVER_ADDRESS=discovery-service

  frontend-nginx:
    build:
      context: uiService
      dockerfile: Prod.Dockerfile
    ports:
      - '1337:80'
