version: "3"
services:

  authentication-db:
    build: authService/authenticationDB
    ports:
      - "27017:27017"
      - "28017:28017"

  delivery-db:
    build: deliveryService/deliveryDB
    ports:
      - "27018:27017"
      - "28018:28017"

  auth-service:
    build: authService

  delivery-service:
    build: deliveryService

  discovery-service:
    build: discoveryService

  gateway-service:
    build: gatewayService
    ports:
      - "8080:8080"

  frontend-nginx:
    build:
      context: uiService
      dockerfile: Prod.Dockerfile
    ports:
      - '1337:80'
