version: "3"
services:

  authentication-db:
    image: authentication-db-docker

  delivery-db:
    image: delivery-db-docker

  discovery-service:
    image: discovery_service-docker
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=discovery-service

  auth-service:
    image: auth_service-docker
    depends_on:
      - authentication-db
      - discovery-service
    environment:
      - EUREKA_SERVER_ADDRESS=discovery-service
      - MONGODB_HOST=authentication-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=auth

  delivery-service:
    image: delivery_service-docker
    depends_on:
      - delivery-db
      - discovery-service
    environment:
      - EUREKA_SERVER_ADDRESS=discovery-service
      - MONGODB_HOST=delivery-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=delivery

  gateway-service:
    image: gateway_service-docker
    ports:
      - "10789:10789"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_SERVER_ADDRESS=discovery-service
      - ORIGIN_URL=http://ec2-35-158-138-25.eu-central-1.compute.amazonaws.com
  
  email-service:
    image: email_service-docker
    environment:
      - EUREKA_SERVER_ADDRESS=email-service

  frontend-nginx:
    image: ui_service-docker
    ports:
      - '80:80'
