image: ubuntu:latest

cache:
  paths:
    - backendParent/.m2/repository
    - backendCommon/target
    - deliveryService/target
    - discoveryService/target
    - authService/target
    - gatewayService/target

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"
  AWS_ECR_BASE_URI: "116161384588.dkr.ecr.eu-central-1.amazonaws.com"

run:
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  image:
    name: linuxserver/openssh-server
    entrypoint: [ "" ]
  stage: deploy
  services:
    - docker:20.10.16-dind
  before_script:
    - echo "Before Script"
    #- echo ${EC2_PEM} > ec2.pem
    - chmod 400 ec2.pem
    #- apt-get -y update 
    #- apt-get -y install openssh-server 

  script: 
    # Push composefile to EC2
    - echo "Push Composefile"
    - scp -tt -o StrictHostKeyChecking=no -i ec2.pem docker-compose.yaml ec2-user@3.73.154.39:online1.yaml

    # Connect to EC2 and download images
    - echo "Connect to EC2"
    - ssh -tt -o StrictHostKeyChecking=no -i ec2.pem ec2-user@3.73.154.39
    - docker pull ${AWS_ECR_BASE_URI}/auth-service:latest
    - docker pull ${AWS_ECR_BASE_URI}/delivery-service:latest
    - docker pull ${AWS_ECR_BASE_URI}/discovery-service:latest
    - docker pull ${AWS_ECR_BASE_URI}/gateway-service:latest
    - docker pull ${AWS_ECR_BASE_URI}/frontend:latest
    - docker pull ${AWS_ECR_BASE_URI}/authentication-db:latest
    - docker pull ${AWS_ECR_BASE_URI}/delivery-db:latest

    # Start Docker container
    - docker-compose down --remove-orphans
    - docker-compose up --abort-on-container-exit






