image: maven:latest

cache:
  paths:
    - backendParent/.m2/repository
    - backendCommon/target
    - deliveryService/target
    - discoveryService/target
    - authService/target
    - gatewayService/target
    - emailService/target

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"
  AWS_ECR_BASE_URI: "116161384588.dkr.ecr.eu-central-1.amazonaws.com"

build:
  stage: build
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn clean $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn $MAVEN_CLI_OPTS test


package:
  stage: deploy
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts: # specified paths in artifacts are saved across jobs
    paths:
      - deliveryService/target
      - discoveryService/target
      - authService/target
      - gatewayService/target
      - emailService/target
    expire_in: 1 week

publish:
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  image:
    name: amazon/aws-cli
    entrypoint: [ "" ]
  stage: deploy
  services:
    - docker:20.10.16-dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script: # build and push images to AWS ECR
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $AWS_ECR_BASE_URI
    - echo "Building auth-service image"
    - docker build -t auth-service  authService/
    - docker tag auth-service:latest ${AWS_ECR_BASE_URI}/auth-service:latest
    - docker push ${AWS_ECR_BASE_URI}/auth-service:latest
    - echo "Building delivery-service image"
    - docker build -t delivery-service  deliveryService/
    - docker tag delivery-service:latest ${AWS_ECR_BASE_URI}/delivery-service:latest
    - docker push ${AWS_ECR_BASE_URI}/delivery-service:latest
    - echo "Building discovery-service image"
    - docker build -t discovery-service  discoveryService/
    - docker tag discovery-service:latest ${AWS_ECR_BASE_URI}/discovery-service:latest
    - docker push ${AWS_ECR_BASE_URI}/discovery-service:latest
    - echo "Building gateway-service image"
    - docker build -t gateway-service  gatewayService/
    - docker tag gateway-service:latest ${AWS_ECR_BASE_URI}/gateway-service:latest
    - docker push ${AWS_ECR_BASE_URI}/gateway-service:latest
    - echo "Building frontend image"
    - docker build -t frontend  uiService/
    - docker tag frontend:latest ${AWS_ECR_BASE_URI}/frontend:latest
    - docker push ${AWS_ECR_BASE_URI}/frontend:latest
    - echo "Building authenticationDB image"
    - docker build -t authentication-db authService/authenticationDB
    - docker tag authentication-db:latest ${AWS_ECR_BASE_URI}/authentication-db:latest
    - docker push ${AWS_ECR_BASE_URI}/authentication-db:latest
    - echo "Building deliveryDB image"
    - docker build -t delivery-db deliveryService/deliveryDB
    - docker tag delivery-db:latest ${AWS_ECR_BASE_URI}/delivery-db:latest
    - docker push ${AWS_ECR_BASE_URI}/delivery-db:latest
    - echo "Building email-service image"
    - docker build -t email-service emailService/
    - docker tag email-service:latest ${AWS_ECR_BASE_URI}/email-service:latest
    - docker push ${AWS_ECR_BASE_URI}/email-service:latest

run:
  image:
    name: linuxserver/openssh-server
  stage: deploy
  before_script:
    - echo "Before Script"
    - chmod 400 ec2.pem

  script:
    # EC2: Stop Compose, delete compose-file, push new compose-file
    - echo "Push Composefile"
    - ssh -tt -o StrictHostKeyChecking=no -i ec2.pem ec2-user@35.158.138.25 "docker-compose down --env-file .env.local --remove-orphans"
    - ssh -tt -o StrictHostKeyChecking=no -i ec2.pem ec2-user@35.158.138.25 "rm -f docker-compose.yaml"

    - scp -o StrictHostKeyChecking=no -i ec2.pem docker-compose.yaml ec2-user@35.158.138.25:docker-compose.yaml
    - scp -o StrictHostKeyChecking=no -i ec2.pem .env.prod ec2-user@35.158.138.25:.env.prod


    # Connect to EC2, login to ECR, download images, start compose
    - echo "Connect to EC2"
    - ssh -tt -o StrictHostKeyChecking=no -i ec2.pem ec2-user@35.158.138.25 "
      
      docker system prune -f --volumes --all;
      
      aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${AWS_ECR_BASE_URI};
      docker pull ${AWS_ECR_BASE_URI}/auth-service:latest;
      docker tag ${AWS_ECR_BASE_URI}/auth-service:latest auth_service-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/delivery-service:latest;
      docker tag ${AWS_ECR_BASE_URI}/delivery-service:latest delivery_service-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/discovery-service:latest;
      docker tag ${AWS_ECR_BASE_URI}/discovery-service:latest discovery_service-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/gateway-service:latest;
      docker tag ${AWS_ECR_BASE_URI}/gateway-service:latest gateway_service-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/email-service:latest;
      docker tag ${AWS_ECR_BASE_URI}/email-service:latest email_service-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/frontend:latest;
      docker tag ${AWS_ECR_BASE_URI}/frontend:latest ui_service-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/authentication-db:latest;
      docker tag ${AWS_ECR_BASE_URI}/authentication-db:latest authentication-db-docker;
      
      docker pull ${AWS_ECR_BASE_URI}/delivery-db:latest;
      docker tag ${AWS_ECR_BASE_URI}/delivery-db:latest delivery-db-docker;
      
      docker-compose --env-file .env.prod up -d"
