image: maven:latest

cache:
  paths:
    - backendParent/.m2/repository
    - backendCommon/target
    - deliveryService/target
    - discoveryService/target
    - authService/target
    - gatewayService/target

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn clean $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn $MAVEN_CLI_OPTS test


package:
  stage: deploy
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    paths:
      - deliveryService/target
      - discoveryService/target
      - authService/target
      - gatewayService/target
    expire_in: 1 week

publish:
  variables:
    # When you use the dind service, you must instruct Docker to talk with
    # the daemon started inside of the service. The daemon is available
    # with a network connection instead of the default
    # /var/run/docker.sock socket. Docker 19.03 does this automatically
    # by setting the DOCKER_HOST in
    # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
    #
    # Specify to Docker where to create the certificates. Docker
    # creates them automatically on boot, and creates
    # `/certs/client` to share between the service and job
    # container, thanks to volume mount from config.toml
    DOCKER_TLS_CERTDIR: "/certs"
  image: docker:20.10.16
  stage: deploy
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
  script:
    - docker build -t auth_service-docker  authService/
    - docker build -t delivery_service-docker  deliveryService/
    - docker build -t discovery_service-docker  discoveryService/
    - docker build -t gateway_service-docker  gatewayService/
    - docker build -t ui_service-docker  uiService/
    - docker build -t authentication-db-docker authService/authenticationDB
    - docker build -t delivery-db-docker deliveryService/deliveryDB

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master
