image: maven:latest

cache:
  paths:
    - backendParent/.m2/repository
    - backendCommon/target
    - deliveryService/target
    - discoveryService/target
    - authService/target
    - gatewayService/target

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn clean $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn $MAVEN_CLI_OPTS test


package:
  stage: deploy
  script:
    - cd "$CI_PROJECT_DIR/backendParent"
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    paths:
      - deliveryService/target
      - discoveryService/target
      - authService/target
      - gatewayService/target
    expire_in: 1 week

publish:
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  image: docker:20.10.16
  stage: deploy
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
  script:
    - docker build -t auth_service-docker  authService/
    - docker push auth_service-docker
    - docker build -t delivery_service-docker  deliveryService/
    - docker push delivery_service-docker
    - docker build -t discovery_service-docker  discoveryService/
    - docker push discovery_service-docker
    - docker build -t gateway_service-docker  gatewayService/
    - docker push gateway_service-docker
    - docker build -t ui_service-docker  uiService/
    - docker push ui_service-docker
    - docker build -t authentication-db-docker authService/authenticationDB
    - docker push authentication-db-docker
    - docker build -t delivery-db-docker deliveryService/deliveryDB
    - docker push delivery-db-docker

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master
