spring:
  application:
    name: auth-service

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

eureka:
  instance:
    hostname: auth-service
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka