# Configuration for the connection string to MongoDB database
spring:
  application:
    name: auth-service
  data:
    mongodb:

      # Configure database location
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      
      # Configure credential
      username: aseAdmin
      password: ase
      authentication-database: admin
      
      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true

server:
  port: ${PORT:8080}
  error:
    include-message: always

eureka:
  instance:
    hostname: auth-service
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka