# Configuration for the connection string to MongoDB database
spring:
  application:
    name: cas-service
  data:
    mongodb:

      # Configure database location
      host: 172.17.0.2
      port: 27017
      database: aseProject
      
      # Configure credential
      username: aseAdmin
      password: ase
      authentication-database: admin
      
      # Configure Database Operation,
      # allow creating index automatically from the code
      auto-index-creation: true

      #enable the usage of Spring Data Mongo Repository
      repositories:
        enabled: true
server:
  port: ${PORT:8080}
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}