# Configuration for the connection string to MongoDB database
spring:
  application:
    name: delivery-service

server:
  port: ${PORT:9091}
  error:
    include-message: always

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka