# Configuration for the connection string to MongoDB database
spring:
  application:
    name: delivery-service

server:
  port: ${PORT:9091}
  error:
    include-message: always

eureka:
  instance:
    hostname: delivery-service
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka