spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ORIGIN_URL} # TODO: add URL of deployed instance here
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - "*"
