spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - "*"

      # TODO: Configure routes to access project services
      routes:
        - id: cas-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/user/**
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/box/**,/delivery/**

server:
  port: ${PORT:10789}
  error:
    include-message: always

eureka:
  instance:
    hostname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka
