spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-proxy
          uri: lb://API-GATEWAY
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: cas-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /user/**, /rfid/**
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/box/**,/delivery/**

server:
  port: ${PORT:10789}
  error:
    include-message: always
    include-binding-errors: always

eureka:
  instance:
    hostname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka
