spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # TODO: add URL of deployed instance here
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - "*"
