spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ORIGIN_URL}
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - "*"
